server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/financial_gateway
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
